service:
  name: voto-limpo-froentend

custom:
  secrets: ${ssm:/aws/reference/secretsmanager/voto-limpo/${self:provider.stage}~true}
  appDomain: ${self:provider.stage}.app.diadovoto.com
  bucketName: "diadovoto-front-${self:custom.appDomain}"
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: build
  scripts:
    hooks:
      'deploy:createDeploymentArtifacts': >
        npm install && REACT_APP_SIGNIN_URI=${self:custom.secrets.SIGNIN_URI}
        REACT_APP_TOKEN_URI=${self:custom.secrets.TOKEN_URI}
        REACT_APP_CLIENT_ID=${self:custom.secrets.MAIN_CLIENT_ID}
        REACT_APP_SELF_URL=https://${self:custom.appDomain}
        REACT_APP_REDIRECT_URI=https://${self:custom.appDomain}/callback
        REACT_APP_BASE_URL=${self:custom.secrets.BASE_URL}
        npm run build

plugins:
  - serverless-s3-sync
  - serverless-pseudo-parameters
  - serverless-plugin-scripts

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 19
  region: eu-west-2
  stage: ${opt:stage, 'dev'}

package:
  include:
    - build/**

resources:
  Resources:
    appBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
    WebAppS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: { Ref: appBucket }
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource: "#{appBucket.Arn}/*"
    myDNS:
      Type: AWS::Route53::RecordSetGroup
      Properties:
        HostedZoneId: ${self:custom.secrets.HOSTED_ZONE_ID}
        Comment: Frontend apps
        RecordSets:
          - Name: "${self:custom.appDomain}"
            Type: AAAA
            AliasTarget:
              DNSName: "#{CloudFrontDistribution.DomainName}"
              # For CloudFront, HostedZoneId is always Z2FDTNDATAQYW2, see:
              # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html#cfn-route53-aliastarget-hostedzoneid
              HostedZoneId:  Z2FDTNDATAQYW2
          - Name: "${self:custom.appDomain}"
            Type: A
            AliasTarget:
              DNSName: "#{CloudFrontDistribution.DomainName}"
              # For CloudFront, HostedZoneId is always Z2FDTNDATAQYW2, see:
              # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html#cfn-route53-aliastarget-hostedzoneid
              HostedZoneId:  Z2FDTNDATAQYW2
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Aliases:
            - "${self:custom.appDomain}"
          Comment: CloudFront Distribution
          DefaultCacheBehavior:
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            TargetOriginId: S3-diadovoto-front-${self:provider.stage}
            ForwardedValues:
              QueryString: "false"
            ViewerProtocolPolicy: redirect-to-https
            DefaultTTL: 30
          IPV6Enabled: true
          Origins:
            - DomainName: "#{appBucket}.s3-website.${self:provider.region}.amazonaws.com"
              Id: S3-diadovoto-front-${self:provider.stage}
              CustomOriginConfig:
                HTTPPort: 80
                OriginProtocolPolicy: http-only
          Enabled: "true"
          DefaultRootObject: index.html
          ViewerCertificate:
            AcmCertificateArn: ${self:custom.secrets.CERTIFICATE_ARN}
            SslSupportMethod: sni-only
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
